### ISSUE TITLE
Error when create project. "Error cleaning up the project:"

### ISSUE THREAD

**Issue by guumo** [SandeepVattapparambil/express-marko-generator#2]
**Describe the bug**
The main command try remove **projectname.git** folder and shows:

> Error cleaning up the project: , rmdir: fallo al borrar 'projectname.git': No existe el archivo o el directorio
rmdir: fallo al borrar '/s': No existe el archivo o el directorio
rmdir: fallo al borrar '/q': No existe el archivo o el directorio

**Comment by Sandeepv68** [comment]
## Thanks for reporting the issue. Happy to know that developers are using my creation.
I have checked the latest version of express-marko-generator from npm and it is working fine on 'Windows'. Please note that unix is not supported yet (Working on it).

If you could give detailed information like:
`OS,
OS version,
Node version,
npm version ,
detailed console log or screenshot of error`
 It would be helpful to resolve faster.

Please report in english

**Comment by guumo** [comment]
Hi! Thanks for your fast reply.

I use:

Ubuntu 18.04.1 LTS
Node 9.11.2
Npm 6.1.0

**Comment by Sandeepv68** [comment]
Ok. I am really sorry to report that, Linux/Unix/Mac support is not yet available now. If you have a windows os, kindly try it on, or else you would have to wait, and i will ping you back once its done.
Feel free to use other tools in the mean time.
